{% set name = "python-louvain" %}
{% set version = "0.14" %}
{% set sha256 = "e0a50c7a1e87b45410cd2a1d6298268862e55edaa46f90ae6b834bbb62df0951" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python
    - networkx
    - numpy

test:
  imports:
    - community

about:
  home: https://github.com/taynaud/python-louvain
  license: None
  summary: Louvain Community Detection
  description: |
    This module implements community detection.

    It uses the louvain method described in Fast unfolding of communities in
    large networks, Vincent D Blondel, Jean-Loup Guillaume, Renaud Lambiotte,
    Renaud Lefebvre, Journal of Statistical Mechanics: Theory and Experiment
    2008(10), P10008 (12pp)

  doc_url: https://python-louvain.readthedocs.io/en/latest/
  dev_url: https://github.com/taynaud/python-louvain

extra:
  recipe-maintainers:
    - ericmjl
    - MridulS
