{% set version = "0.16" %}

package:
  name: python-louvain
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-louvain/python-louvain-{{ version }}.tar.gz
  sha256: b7ba2df5002fd28d3ee789a49532baad11fe648e4f2117cf0798e7520a1da56b
  patches:
    - 0000-use-entry-points.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -c "__import__('pathlib').Path('bin/community').rename('community/_cli.py')"
    - {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - community = community._cli:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - networkx
    - numpy
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - community
  commands:
    - pip check
    # has no --version or --help, just check if it ends up on $PATH
    - which community || where community

about:
  home: https://github.com/taynaud/python-louvain
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Louvain Community Detection
  description: |
    This module implements community detection.

    It uses the louvain method described in Fast unfolding of communities in
    large networks, Vincent D Blondel, Jean-Loup Guillaume, Renaud Lambiotte,
    Renaud Lefebvre, Journal of Statistical Mechanics: Theory and Experiment
    2008(10), P10008 (12pp)

  doc_url: https://python-louvain.readthedocs.io/en/latest/
  dev_url: https://github.com/taynaud/python-louvain

extra:
  recipe-maintainers:
    - ericmjl
    - MridulS
    - bollwyvl
