{% set name = "python-louvain" %}
{% set version = "0.12" %}
{% set sha256 = "9e6601ff245123421a4b0e23b58fc0f780f18b8311feecb7de81ad432299de49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python
    - networkx

test:
  imports:
    - community

about:
  home: https://github.com/taynaud/python-louvain
  license: None
  summary: 'Louvain Community Detection'
  description: |
    This module implements community detection.

    It uses the louvain method described in Fast unfolding of communities in
    large networks, Vincent D Blondel, Jean-Loup Guillaume, Renaud Lambiotte,
    Renaud Lefebvre, Journal of Statistical Mechanics: Theory and Experiment
    2008(10), P10008 (12pp)

  doc_url: https://python-louvain.readthedocs.io/en/latest/
  dev_url: https://github.com/taynaud/python-louvain

extra:
  recipe-maintainers:
    - ericmjl
    - MridulS
